apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
    namespace: myapp
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  hostPath:
    path: /tmp/db