name: k8s_test

on:
  push:
    branches:
      - master
    paths:
      - k8s_test/**

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Create Namespace
        run: kubectl create namespace myapp       
      - name: Deploy to minikube
        run: |
          cd k8s_test
          kubectl apply -f mongo_pv_test.yaml 
          kubectl apply -f mongo_pvc_test.yaml 
          kubectl apply -f mongodb_storageclass_test.yaml
          kubectl apply -f deployment_test.yaml

      - name: Check Events
        run: kubectl get events -n myapp

      - name: Describe PVCs
        run: kubectl describe pvc -n myapp
      
      - name: Check PVs
        run: kubectl get pv

      - name: Check Storage Classes
        run: kubectl get sc
      
      - name: Check Logs of market-app
        run: kubectl logs -l app=market-app -n myapp
      
      - name: Check Logs of mongodb
        run: kubectl logs -l app=mongodb -n myapp
      
      - name: Test service URLs
        run: |
          minikube service list
          minikube service market-app-service -n myapp --url
          echo "------------------opening the service------------------"
          curl $(minikube service market-app-service -n myapp --url)
  
