name: k8s_test

on:
  push:
    branches:
      - master
    paths:
      - k8s_test/**

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Create Namespace
        run: kubectl create namespace myapp       
      - name: Deploy to minikube
        run: |
          cd k8s_test
          kubectl apply -f mongo_pv_test.yaml 
          kubectl apply -f mongo_pvc_test.yaml 
          kubectl apply -f mongodb_storageclass_test.yaml
          kubectl apply -f deployment_test.yaml

      - name: Test Docker Image Pull
        run: docker pull lironderi/market-app:v1.0.6100584626
              
      - name: Get Network Policies
        run: kubectl get networkpolicy -n myapp
     
      - name: Check Node Resources
        run: kubectl describe node minikube
       
      - name: Get Application Logs
        run: kubectl logs -l app=market-app -n myapp
      

      
        
      - name: Test service URLs
        run: |
          minikube service list
          minikube service market-app-service -n myapp --url
          echo "------------------opening the service------------------"
          curl $(minikube service market-app-service -n myapp --url)
  
