name: Deploy Infrastructure 
on: 
  push:
    branches:
      - master
    paths: 
    - eks_conf/**
    - argo-cd_conf/**

env:      
    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy_infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: "hello"
    env:
      TF_WORKSPACE: staging
      TF_VAR_hola: "ma nishma motek"

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # TF_ACTION_WORKING_DIR: "eks_conf"

    - name: pwd
      id: pwd
      run: pwd



    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: ls
      id: ls
      run: |
         ls -lR 
      
    # - name: Terraform Validate
    #   id: validate
    #   run: terraform validate -no-color
      
    # - name: Terraform Plan
    #   id: plan
    #   run: |
    #     terraform plan -no-color
    #   continue-on-error: true

    

    - name: Terraform Apply
      id: apply
      run: |
        for i in {1..5}
        do
          terraform apply -auto-approve || sleep 10
        done

    - name: ls
      id: ls2
      run: |
         ls -lR 


    # - name: apply ALB
    #   run: |
    #     cd ../alb
    #     terraform init
    #     terraform apply -auto-approve


    
    # - name: Terraform destroy
    #   if: always()
    #   id: destroy
    #   run: |
    #     terraform destroy -auto-approve




  # deploy_argo:
  #     needs: deploy_infrastructure
  #     name: Deploy argo
  #     runs-on: ubuntu-latest
  #     defaults:
  #       run:
  #         working-directory: "argo-cd_conf"
  #     steps:

  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Terraform Setup
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #           terraform_version: 1.3.0
  #       env:
  #           GH_TOKEN: ${{ secrets.GH_TOKEN }}
                
  #     - name: Terraform Init
  #       id: init
  #       run: terraform init
        
        
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate -no-color
        
  #     - name: Terraform Plan
  #       id: plan
  #       run: terraform plan -no-color
  #       continue-on-error: true